### ISSUE TITLE
GeoStyler Docs missing images, every code example broken

### ISSUE THREAD

**Issue by jodygarnett** [terrestris/geostyler#1170]
Good afternoon, I am getting ready for a FOSS4G keynote and would like to give a shout-out to the GeoStyler project (thank you!).

Reading the GeoStyler Documentation: https://terrestris.github.io/geostyler/

* [x] Broken Image for "GeoStyler Logo" at the top of the page
* [x] [editor](https://terrestris.github.io/geostyler/latest/index.html#editor) has broken code example
  
  > This demonstrates the use of Editor.
  > ```
  > SyntaxError: Unexpected token (32:18)
  > 28 :     } = this.state;
  > 29 : 
  > 30 :     return (
  > 31 :       <Editor
  > 32 :         symbolizer={symbolizer}
  > ```
* [x] [ImageField](https://terrestris.github.io/geostyler/latest/index.html#imagefield) has broken code example
  
  > This demonstrates the use of Editor.
  > ```
  > SyntaxError: Unexpected token (26:13)
  > 22 :     } = this.state;
  > 23 : 
  > 24 :     return (
  > 25 :       <ImageField
  > 26 :         value={value}

Indeed every demonstration code example is broken at this time ...

**Comment by jansule** [comment]
Thanks for pointing out the errors. 

Broken examples were already mentioned in https://github.com/terrestris/geostyler/issues/1158. Currently, there seems to be a problem with the latest styleguidist version as can be seen in https://github.com/styleguidist/react-styleguidist/issues/1321. Downgrading styleguidist and other dependencies did fix building the documentation but led to unexpected sideeffects regarding other parts of the ci (see https://github.com/terrestris/geostyler/pull/1157).

We are trying to solve this problem asap.

The broken image was fixed in https://github.com/terrestris/geostyler/pull/1165. It can be already seen in the [`master documentation`](https://terrestris.github.io/geostyler/master/index.html). Should be fixed for the `latest documentation` with the upcoming release.

By the way, really thrilled you are going to mention GeoStyler at your keynote!

**Comment by jansule** [comment]
@jodygarnett issues were fixed in #1174. Please be aware that until there will be a new release, only the [masterdocs](https://terrestris.github.io/geostyler/master/index.html) are working.

- [Editor](https://terrestris.github.io/geostyler/master/index.html#editor)
- [ImageField](https://terrestris.github.io/geostyler/master/index.html#imagefield)

**Comment by KaiVolland** [comment]
I think this can be closed for now.
