### ISSUE TITLE
Enhance typing in rules name field

### ISSUE THREAD

**Issue by marcjansen** [terrestris/geostyler#234]
When one types in the name field of the rule of the [example application](https://terrestris.github.io/geostyler/), the textfield looses the focus, and the map gets reloaded completely.

It'd be nice 
* if the field didn't loose focus, so one can type more than one character
* if the map would not do a full reload

**Comment by KaiVolland** [comment]
This is really strange.
I can't figure out the difference on the rules name property. Every other property just works fine and doesn't lead to this strange behaviour...

**Comment by chrismayer** [comment]
I found the reason why this all happens:

In `Style.tsx` the rule UIs are created dynamically and their name is used as `key` property. This means the key changes every time you are typing in the input field and React throws away the old input and adds a new input in its place. It looks identical, but it looses the focus.

Here you can find a blog post reporting the same behavior:  http://reactkungfu.com/2015/09/react-js-loses-input-focus-on-typing/

The following code solves the problem:
```
{
    rules.map((rule, idx) => <Rule
      key={'rule_' + idx}
      rule={rule}
      onRemove={this.removeRule}
      internalDataDef={this.props.data}
      onRuleChange={this.onRuleChange}
    />)
} 
```

@KaiVolland since you did a lot on this : Are you OK with this or am I missing something by changing the key like above?

**Comment by KaiVolland** [comment]
Please merge if this does the trick.
