### ISSUE TITLE
Implement a Symbolizer preview UI

### ISSUE THREAD

**Issue by chrismayer** [terrestris/geostyler#81]
We need to add a a ``Symbolizer`` preview UI showing the currently active style for the geometries.

It has to be cleared if this should be done with OpenLayers (which needs a TypeScript binding for OL) or by native TypeScript (with canvas drawing or similar).

The UI should look like this (POINT / LINE / POLYGON):

![image](https://user-images.githubusercontent.com/1185547/40350079-e54519a8-5da8-11e8-8f55-c2b8c0e39cc9.png)
![image](https://user-images.githubusercontent.com/1185547/40350091-f635325c-5da8-11e8-8405-3f2d00333c84.png)
![image](https://user-images.githubusercontent.com/1185547/40350120-07543966-5da9-11e8-9b1c-f462c14b2145.png)

**Comment by marcjansen** [comment]
I would add that we want the possibility to use 

* many realworld geometries as preview geometries (from a vector source)
* a service for preview (e.g. a WMS)

In such cases the map for the preview should be configurable, so that other layers to show up can be configured and things like projection and extebt can be changed. @weskamm should weigh in here, he created our last project solutions. Don't get me wrong, we can start easy, as long as we have ways to achieve the above with additional work.

**Comment by chrismayer** [comment]
Thanks for the additions @marcjansen! Since now it is clear that the final solutions will be a more complex map, we should use OpenLayers for the style preview from the beginning.

**Comment by KaiVolland** [comment]
Can this be closed as #92 is merged?

**Comment by chrismayer** [comment]
Yes, I think we can close this.
